# Generated by Django 4.2.26 on 2025-11-18 13:34

from django.db import migrations


def transfer_data_forward(apps, schema_editor):
    """Transférer les données de oc_lettings_site vers profiles"""
    # Récupérer les anciens modèles  
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    
    # Récupérer les nouveaux modèles
    NewProfile = apps.get_model('profiles', 'Profile')
    
    # Transférer les profils avec préservation des IDs et relations User
    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            id=old_profile.id,
            user=old_profile.user,  # Relation User préservée
            favorite_city=old_profile.favorite_city,
        )


def transfer_data_reverse(apps, schema_editor):
    """Fonction de rollback - supprime les données transférées"""
    NewProfile = apps.get_model('profiles', 'Profile')
    NewProfile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),  # Dépendance sur les anciennes tables
    ]

    operations = [
        migrations.RunPython(
            transfer_data_forward,
            transfer_data_reverse,
        ),
    ]
