# Generated by Django 4.2.26 on 2025-11-18 13:34

from django.db import migrations


def transfer_data_forward(apps, schema_editor):
    """Transférer les données de oc_lettings_site vers lettings"""
    # Récupérer les anciens modèles
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    
    # Récupérer les nouveaux modèles
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')
    
    # Transférer les adresses avec préservation des IDs
    for old_address in OldAddress.objects.all():
        NewAddress.objects.create(
            id=old_address.id,
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )
    
    # Transférer les lettings avec relations préservées
    for old_letting in OldLetting.objects.all():
        new_address = NewAddress.objects.get(id=old_letting.address_id)
        NewLetting.objects.create(
            id=old_letting.id,
            title=old_letting.title,
            address=new_address,
        )


def transfer_data_reverse(apps, schema_editor):
    """Fonction de rollback - supprime les données transférées"""
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')
    
    NewLetting.objects.all().delete()
    NewAddress.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),  # Dépendance sur les anciennes tables
    ]

    operations = [
        migrations.RunPython(
            transfer_data_forward,
            transfer_data_reverse,
        ),
    ]
