# Generated by Django 4.2.26 on 2025-11-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0001_initial'),
        ('lettings', '0002_transfer_data'),
        ('profiles', '0002_transfer_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
